---
name: Pre-release

on: push
#  push:
#    branches:
#      - "master"

jobs:
  pre-release:
    name: Pre Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          override: true
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target=x86_64-pc-windows-gnu

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.RELEASE_TOKEN }}"
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            target/x86_64-pc-windows-gnu/release/reverb.dll
